### ISSUE TITLE
Concatenation feature

### ISSUE THREAD

**Issue by adzymaniac** [JeffreyWay/laravel-elixir-stylus#11]
Hi,

I use stylus in separated files, but when translate my gulpfiles to elixir i have a problem with compilation because 1 of my file is all variables for my another files. I notice it because `laravel-elixir-stylus` just compile every single file, not concat first like `mix.styles` or `mix.scripts` do.

I'm trying to solve this problem, but not "right way" because my modification just install gulp-concat as dependency and concat all files before stylus compilation. The `paths.output` not as expected.

What do you think? Thanks.

**Comment by JeffreyWay** [comment]
Can you try upgrading to the latest version of Elixir 3 and this extension? Should work for you, I think.
