### ISSUE TITLE
Error: Cannot find module 'laravel-elixir/tasks/shared/Css'

### ISSUE THREAD

**Issue by aguilarcarlos** [JeffreyWay/laravel-elixir-stylus#12]
Module 'laravel-elixir/tasks/shared/Css' not found in laravel-elixir when trying compile with gulp.

**Comment by JeffreyWay** [comment]
Sounds like you're not using Elixir ^3.0. Bump up to that release, and you should be good to go.

**Comment by canvural** [comment]
I still get this error with Elixir 6.

**Comment by xmoki** [comment]
i can confirm this, this error happens if using laravel-elixir@^6.0.0-1 and not when using 5.0.0 or below.
