### ISSUE TITLE
Error: Cannot find module 'laravel-elixir/dist/tasks/CssTask'

### ISSUE THREAD

**Issue by siangboon** [JeffreyWay/laravel-elixir-stylus#23]
After installed and configured laravel-elixir-stylus according to the installation guideline and I ran the **gulp** command and get the the error message:

> C:\Websites\deve> **npm list | findstr elixir**
> +-- laravel-elixir@6.0.0-2
> `-- laravel-elixir-stylus@2.0.2
> 
> C:\Websites\deve\beautifulas.com>**gulp**
> module.js:341
>     throw err;
>     ^
> 
> Error: Cannot find module 'laravel-elixir/dist/tasks/CssTask'
>     at Function.Module._resolveFilename (module.js:339:15)
>     at Function.Module._load (module.js:290:25)
>     at Module.require (module.js:367:17)
>     at require (internal/module.js:16:19)
>     at Object.<anonymous> (C:\Websites\deve\node_modules\laravel-elixir-stylus\index.js:1:77)
>     at Module._compile (module.js:413:34)
>     at Object.Module._extensions..js (module.js:422:10)
>     at Module.load (module.js:357:32)
>     at Function.Module._load (module.js:314:12)
>     at Module.require (module.js:367:17)

but once i disabled stylus and change to scss and it compiled successfully.

**Comment by RyanFergerson** [comment]
+1 Ran into this issue as well

**Comment by terion-name** [comment]
@JeffreyWay With Elixir 6 base task can be called with `var compile = require('laravel-elixir/dist/tasks/shared/Css').default;` (or `import compile from 'laravel-elixir/dist/tasks/shared/Css'`).

This can be fixed with simple PR, but I don't know what is a better way to retain backward compatibility (if it is needed, of course). Testing for file presence with `fs`? Doesn't look good..

**Comment by terion-name** [comment]
@siangboon @RyanFergerson as a temporary fix - to copy the stylus plugin rom node_modules somewhere in your app, change the import as mentioned above and require this file instead of a module

**Comment by thasmog** [comment]
+1 Ran into this issue as well

`Error: Cannot find module 'laravel-elixir/dist/tasks/CssTask'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/vagrant/Code/hiphop/node_modules/laravel-elixir-stylus/index.js:1:77)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
`

**Comment by guillaumezeeman** [comment]
+1 I too am experiencing this problem.

**Comment by nickclasener** [comment]
Have spent the last 3 hours trying to fix this found it in the readme 
[laravel-elixir-stylus](https://github.com/JeffreyWay/laravel-elixir-stylus)

> Note: if using Laravel Elixir 6 or higher, pull in laravel-elixir-stylus@2.x. Otherwise, stick with laravel-elixir-stylus@1.x

Got to love the process of learning xD

**Comment by fdeneux** [comment]
+1 Having the same issue

```
"laravel-elixir": "^6.0.0-2",
"laravel-elixir-stylus": "^2.0.2",
```

**Comment by JeffreyWay** [comment]
The version of Elixir that works with the latest release of this package hasn't been tagged yet.

Elixir 6 isn't out yet. You should use 5 or below with 1.x of this package for now.

**Comment by terion-name** [comment]
@JeffreyWay elixir6 is installed with fresh Laravel automatically

**Comment by JeffreyWay** [comment]
https://github.com/laravel/laravel/blob/master/package.json#L9

**Comment by terion-name** [comment]
very strange, it's unclear how all people here (including me) got `^6.0.0-2`. but problem is clear now, thank you
