### ISSUE TITLE
Update LostGrid dependency

### ISSUE THREAD

**Issue by perkola** [JeffreyWay/laravel-elixir-stylus#27]
LostGrid has moved into [releasing version `7.0.*`](https://github.com/peterramsing/lost/releases) and it has some smaller new features but most important, a lot of bug fixes. It would be nice if the dependency could be upgraded. 

Thank you.

**Comment by JeffreyWay** [comment]
Great. Would you mind submitting a PR?

**Comment by perkola** [comment]
PR submitted. See #29
