### ISSUE TITLE
stylus does not respect elixir.config.assetsDir option

### ISSUE THREAD

**Issue by terion-name** [JeffreyWay/laravel-elixir-stylus#30]
I have a custom place for assets:
```
elixir.config.assetsDir = 'resources/assets/app/';
```

This affects other tasks, but not stylus. Currently I workaround this with such setup:
```
mix.stylus('../app/stylus/app.styl', 'public/assets/app/css/app.css');
```

But obviously `assetsDir` option should be respected.

**Comment by JeffreyWay** [comment]
It should respect it. Are you updating `elixir.config.assetsDir` before or after you require this package in your Gulpfile?

**Comment by terion-name** [comment]
I've had this:

```js
// elixir.conig.js
const elixir = require('laravel-elixir');
elixir.ready(()=>{
    "use strict";
    elixir.config.assetsDir = 'resources/assets/app/';
```
```js
// gulpfile.js
require('laravel-elixir-stylus');
require('./elixir.config');
```

Now I've tried to move `assetsDir` setting out of `ready` callback, moved `require('./elixir.config')` before or after `require('laravel-elixir-stylus')` — all the same

**Comment by JeffreyWay** [comment]
Do:

```js
elixir(mix => {
    elixir.config.assetsPath = 'app/assets';
    
    mix.stylus('app.styl');
});
```
