### ISSUE TITLE
Add new argument to add extra parameters to stylus

### ISSUE THREAD

**Issue by Arrogance** [JeffreyWay/laravel-elixir-stylus#9]
Hi,

I forked the repository and I'm working in a little modification to add the possibility of extra arguments to stylus. Ex:

```javascript
.stylus({
    use: [nib()],
    errors: true
})
```

Etcetera. Passing a new argument to ```elixir.extend('stylus', function(src, output, extra)```

**Comment by thiagocoelho** [comment]
This is very useful, I'm using a custom task now because I'm unable to pass options to stylus.

:+1: 

@JeffreyWay What do you think?

**Comment by JeffreyWay** [comment]
You can do:

```
mix.stylus('app.styl', null, { use: [] });
```
